set(CMAKE_SYSTEM_NAME unhosted)
set(CMAKE_SYSTEM_VERSION 1.0.0)  # bogus
set(CMAKE_SYSTEM_PROCESSOR "${TARGET_PROCESSOR}")

set(CMAKE_STAGING_PREFIX "${REPOSITORY_ROOT}/build/${TARGET_PROCESSOR}")

set(CMAKE_C_COMPILER "${COMPILER}")
set(CMAKE_NASM_COMPILER "${ASSEMBLER}")
set(CMAKE_C_LINKER "${LINKER}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
