/**
 * Define the real C standard errno values if we're not testing against the host.
 *
 * @file errno.h
 */

#ifndef INCLUDE_METALC_BITS_ERRNO_H_
#define INCLUDE_METALC_BITS_ERRNO_H_

#ifndef METALC_DISABLE_STDLIB_DEFS
#    define EPERM mclib_EPERM
#    define ENOENT mclib_ENOENT
#    define ESRCH mclib_ESRCH
#    define EINTR mclib_EINTR
#    define EIO mclib_EIO
#    define ENXIO mclib_ENXIO
#    define E2BIG mclib_E2BIG
#    define ENOEXEC mclib_ENOEXEC
#    define EBADF mclib_EBADF
#    define ECHILD mclib_ECHILD
#    define EAGAIN mclib_EAGAIN
#    define EWOULDBLOCK mclib_EWOULDBLOCK
#    define ENOMEM mclib_ENOMEM
#    define EACCES mclib_EACCES
#    define EFAULT mclib_EFAULT
#    define ENOTBLK mclib_ENOTBLK
#    define EBUSY mclib_EBUSY
#    define EEXIST mclib_EEXIST
#    define EXDEV mclib_EXDEV
#    define ENODEV mclib_ENODEV
#    define ENOTDIR mclib_ENOTDIR
#    define EISDIR mclib_EISDIR
#    define EINVAL mclib_EINVAL
#    define ENFILE mclib_ENFILE
#    define EMFILE mclib_EMFILE
#    define ENOTTY mclib_ENOTTY
#    define ETXTBSY mclib_ETXTBSY
#    define EFBIG mclib_EFBIG
#    define ENOSPC mclib_ENOSPC
#    define ESPIPE mclib_ESPIPE
#    define EROFS mclib_EROFS
#    define EMLINK mclib_EMLINK
#    define EPIPE mclib_EPIPE
#    define EDOM mclib_EDOM
#    define ERANGE mclib_ERANGE
#    define EDEADLK mclib_EDEADLK
#    define EDEADLOCK mclib_EDEADLOCK
#    define ENAMETOOLONG mclib_ENAMETOOLONG
#    define ENOLCK mclib_ENOLCK
#    define ENOSYS mclib_ENOSYS
#    define ENOTEMPTY mclib_ENOTEMPTY
#    define ELOOP mclib_ELOOP
#    define ENOMSG mclib_ENOMSG
#    define EIDRM mclib_EIDRM
#    define ECHRNG mclib_ECHRNG
#    define EL2NSYNC mclib_EL2NSYNC
#    define EL3HLT mclib_EL3HLT
#    define EL3RST mclib_EL3RST
#    define ELNRNG mclib_ELNRNG
#    define EUNATCH mclib_EUNATCH
#    define ENOCSI mclib_ENOCSI
#    define EL2HLT mclib_EL2HLT
#    define EBADE mclib_EBADE
#    define EBADR mclib_EBADR
#    define EXFULL mclib_EXFULL
#    define ENOANO mclib_ENOANO
#    define EBADRQC mclib_EBADRQC
#    define EBADSLT mclib_EBADSLT
#    define EBFONT mclib_EBFONT
#    define ENOSTR mclib_ENOSTR
#    define ENODATA mclib_ENODATA
#    define ETIME mclib_ETIME
#    define ENOSR mclib_ENOSR
#    define ENONET mclib_ENONET
#    define ENOPKG mclib_ENOPKG
#    define EREMOTE mclib_EREMOTE
#    define ENOLINK mclib_ENOLINK
#    define EADV mclib_EADV
#    define ESRMNT mclib_ESRMNT
#    define ECOMM mclib_ECOMM
#    define EPROTO mclib_EPROTO
#    define EMULTIHOP mclib_EMULTIHOP
#    define EDOTDOT mclib_EDOTDOT
#    define EBADMSG mclib_EBADMSG
#    define EOVERFLOW mclib_EOVERFLOW
#    define ENOTUNIQ mclib_ENOTUNIQ
#    define EBADFD mclib_EBADFD
#    define EREMCHG mclib_EREMCHG
#    define ELIBACC mclib_ELIBACC
#    define ELIBBAD mclib_ELIBBAD
#    define ELIBSCN mclib_ELIBSCN
#    define ELIBMAX mclib_ELIBMAX
#    define ELIBEXEC mclib_ELIBEXEC
#    define EILSEQ mclib_EILSEQ
#    define ERESTART mclib_ERESTART
#    define ESTRPIPE mclib_ESTRPIPE
#    define EUSERS mclib_EUSERS
#    define ENOTSOCK mclib_ENOTSOCK
#    define EDESTADDRREQ mclib_EDESTADDRREQ
#    define EMSGSIZE mclib_EMSGSIZE
#    define EPROTOTYPE mclib_EPROTOTYPE
#    define ENOPROTOOPT mclib_ENOPROTOOPT
#    define EPROTONOSUPPORT mclib_EPROTONOSUPPORT
#    define ESOCKTNOSUPPORT mclib_ESOCKTNOSUPPORT
#    define ENOTSUP mclib_ENOTSUP
#    define EOPNOTSUPP mclib_EOPNOTSUPP
#    define EPFNOSUPPORT mclib_EPFNOSUPPORT
#    define EAFNOSUPPORT mclib_EAFNOSUPPORT
#    define EADDRINUSE mclib_EADDRINUSE
#    define EADDRNOTAVAIL mclib_EADDRNOTAVAIL
#    define ENETDOWN mclib_ENETDOWN
#    define ENETUNREACH mclib_ENETUNREACH
#    define ENETRESET mclib_ENETRESET
#    define ECONNABORTED mclib_ECONNABORTED
#    define ECONNRESET mclib_ECONNRESET
#    define ENOBUFS mclib_ENOBUFS
#    define EISCONN mclib_EISCONN
#    define ENOTCONN mclib_ENOTCONN
#    define ESHUTDOWN mclib_ESHUTDOWN
#    define ETOOMANYREFS mclib_ETOOMANYREFS
#    define ETIMEDOUT mclib_ETIMEDOUT
#    define ECONNREFUSED mclib_ECONNREFUSED
#    define EHOSTDOWN mclib_EHOSTDOWN
#    define EHOSTUNREACH mclib_EHOSTUNREACH
#    define EALREADY mclib_EALREADY
#    define EINPROGRESS mclib_EINPROGRESS
#    define ESTALE mclib_ESTALE
#    define EUCLEAN mclib_EUCLEAN
#    define ENOTNAM mclib_ENOTNAM
#    define ENAVAIL mclib_ENAVAIL
#    define EISNAM mclib_EISNAM
#    define EREMOTEIO mclib_EREMOTEIO
#    define EDQUOT mclib_EDQUOT
#    define ENOMEDIUM mclib_ENOMEDIUM
#    define EMEDIUMTYPE mclib_EMEDIUMTYPE
#    define ECANCELED mclib_ECANCELED
#    define ENOKEY mclib_ENOKEY
#    define EKEYEXPIRED mclib_EKEYEXPIRED
#    define EKEYREVOKED mclib_EKEYREVOKED
#    define EKEYREJECTED mclib_EKEYREJECTED
#    define EOWNERDEAD mclib_EOWNERDEAD
#    define ENOTRECOVERABLE mclib_ENOTRECOVERABLE
#    define ERFKILL mclib_ERFKILL
#    define EHWPOISON mclib_EHWPOISON
#endif /* METALC_DISABLE_STDLIB_DEFS */
#endif /* INCLUDE_METALC_BITS_ERRNO_H_ */
