REPO_ROOT:=${REPO_ROOT}
OPERATING_SYSTEM_PLATFORM_ISH:=${HOST_PLATFORM}
ABI:=${ABI}
GCC_TOOLCHAIN_TRIPLE:=${TARGET_ARCHITECTURE_SLUG}-${HOST_PLATFORM}-${ABI}
% if HOST_PLATFORM == "windows"
% elif HOST_PLATFORM == "darwin"
% else
    %# Linux
% endif
